# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/amperser/proselint
    rev: 0.14.0
    hooks:
      - id: proselint
        files: \.(md|txt|rst|adoc)$ # Adjust file extensions as needed
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
